name: cloudwalk_mobile_test_app

packages:
  - "apps/apod"
  - "packages/**/**"

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  test:
    run: melos exec --fail-fast -- "flutter test" --no-pub
    description: Run Flutter tests for a specific package in this workspace.
    packageFilters:
      dirExists: test

  codegen:
    run: melos exec -c 1 --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for specific package
    packageFilters:
      dependsOn: build_runner

  codegen:all:
    run: melos run codegen --no-select

  post clean: melos exec -c 6 -- "flutter clean" && melos run clean:codegen

  clean:codegen:
    run: melos exec -- "sh \$MELOS_ROOT_PATH/scripts/clean_codegen.sh"
    description: Clean up all generated files from packages
    packageFilters:
      dependsOn: build_runner

  analyze:
    run: melos exec -c 5 dart analyze .
    description: Run `dart analyze` in all packages.

  format:
    run: melos exec -- "dart format . --set-exit-if-changed"
    description: Run `dart format .` in all packages

  lint:
    run: melos run analyze && melos run format
    description: Run all static analysis checks

  fix:
    run: melos exec dart fix --apply
    description: Fix all problems in packages
