name: feature_media
description: Domain business rules for handling media
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_commons:
    path: "../../core/core_commons"

  core_dependencies:
    path: "../../core/core_dependencies"

  core_network:
    path: "../../core/core_network"

  core_di:
    path: "../../core/core_di"

  ui_core:
    path: "../../ui/ui_core"

  feature_core:
    path: "../feature_core"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

  core_test:
    path: "../../core/core_test"

flutter:
