name: feature_core
description: Common code and structure for features
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_dependencies:
    path: "../../core/core_dependencies"

  core_commons:
    path: "../../core/core_commons"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
