name: ui_media
description: apod media user interfaces
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core_commons:
    path: "../../core/core_commons"

  core_dependencies:
    path: "../../core/core_dependencies"

  feature_media:
    path: "../../feature/feature_media"

  ui_core:
    path: "../ui_core"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
