name: "Code Quality Workflow"

on:
  push:
    branches: [main]

jobs:
  code_quality:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Get Repository
        uses: actions/checkout@v3

      - name: Setup FVM
        uses: kuhnroyal/flutter-fvm-config-action@v1
        id: fvm-config-action

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Create .env file
        run: cd apps/shell && touch .env
        shell: bash

      - name: Setup tools
        run: |
          dart pub global activate melos
          dart pub global activate remove_from_coverage

      - name: Clean Workspace
        run: melos clean

      - name: Bootstrap Workspace
        run: melos bootstrap --verbose

      - name: Run dart analyze & format
        run: melos lint

      - name: Validate Formatting
        run: sh .github/scripts/validate_formatting.sh

      - name: Run unit tests
        run: melos test
